[project]
name = "prompt_evolution"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kagglehub>=0.3.12",
    "ollama>=0.4.8",
    "pandas>=2.2.3",
]
